services:
  train-yolo:
    build:
      context: .
      dockerfile: dockerfile
      args:
        BASE_IMAGE: dustynv/l4t-pytorch:r36.4.0
    container_name: home2-vision-yolo
    image: roborregos/home2:vision-yolo
    volumes:
      - ./notebooks:/content/notebooks
      - ./content:/content
    ports:
      - "8888:8888"
    network_mode: host
    runtime: nvidia
    shm_size: 16g
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''