networks:
  yolo-home-net:
    name: yolo-home-net

services:
  train-yolo:
    build:
      context: .
      dockerfile: dockerfile
      args:
        BASE_IMAGE: pytorch/pytorch:latest
    container_name: home2-vision-yolo
    image: roborregos/home2:vision-yolo
    volumes:
      - ./notebooks:/content/notebooks
      - ./content:/content
    ports:
      - "8888:8888"
    runtime: nvidia
    shm_size: 32gb
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    networks:
      - yolo-home-net
