networks:
  yolo-home-net:
    name: yolo-home-net

services:
  train-yolo:
    build:
      context: .
      dockerfile: dockerfile
      args:
        BASE_IMAGE: pytorch/pytorch:latest
    container_name: home2-vision-yolo
    image: roborregos/home2:vision-yolo
    volumes:
      - ./notebooks:/content/notebooks
      - ./content:/content
      - ./:/app
    ports:
      - "8888:8888"
    runtime: nvidia
    shm_size: 32gb
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    networks:
      - yolo-home-net

  pipeline-service:
    build:
      context: .
      dockerfile: service.dockerfile
      args:
        BASE_IMAGE: pytorch/pytorch:latest
    container_name: home2-vision-service
    image: roborregos/home2:vision-service
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    runtime: nvidia
    shm_size: 32gb
    working_dir: /app
    environment:
      - PIPELINE_API_KEY=${PIPELINE_API_KEY:-TESTING*/*1234567890}
      - PYTHONPATH=/app/models/sam3
    command: uvicorn service:app --host 0.0.0.0 --port 8000 --workers 1
    networks:
      - yolo-home-net
