ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /content

RUN pip install jupyter jupyterlab
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y git

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8889", "--no-browser", "--allow-root"]